import { appConfig } from "./auth/app.configs";

export class tenantDetails {
  Active: boolean;
  ApiKey: string;
  Banner1: string;
  Banner2: string;
  CollegeName: string;
  CreatedBy: string;
  CreatedOn: any;
  CurrentPlan: string;
  Deleted: boolean;
  Email: string;
  FirstName: string;
  Id: string;
  LastName: string;
  Logo:string;
  OrderNo: number;
  Password: string;
  PlanID: string;
  PostBanner1: string;
  PostBanner2: string;
  PostLogo: string;
  PreviousPlan: string;
  SchemaID: string;
  Slogan: string;
  StateId: number;
  SubDomain: string;
  SubscriptionExpiredOn: string;
  SubscriptionRenewedAt: string;
  SubscriptionStartOn: string;
  SubscriptionStatus: any;
  SupportEmail: string;
  SupportPhoneNumber: string;
  ThemeID:string;
  UpdatedBy: any;
  UpdatedOn: any;
  constructor(tenantDetails){
    this.Active = tenantDetails.Active || false;
    this.ApiKey = tenantDetails.ApiKey || '';
    this.Banner1 = tenantDetails.Banner1 || '';
    this.Banner2 = tenantDetails.Banner2 || '';
    this.CollegeName = tenantDetails.CollegeName || '';
    this.CreatedBy = tenantDetails.CreatedBy || '';
    this.CreatedOn = tenantDetails.CreatedOn || null;
    this.CurrentPlan = tenantDetails.CurrentPlan || '';
    this.Deleted = tenantDetails.Deleted || false;
    this.Email = tenantDetails.Email || '';
    this.FirstName = tenantDetails.FirstName || '';
    this.Id = tenantDetails.Id || '';
    this.LastName = tenantDetails.LastName || '';
    this.Logo = tenantDetails.Logo ||appConfig.CollegeLogo.collegeLogo; 
    this.OrderNo = tenantDetails.OrderNo || 0;
    this.Password = tenantDetails.Password || '';
    this.PlanID = tenantDetails.PlanID || '';
    this.PostBanner1 = tenantDetails.PostBanner1 || '';
    this.PostBanner2 = tenantDetails.PostBanner2 || '';
    this.PostLogo = tenantDetails.PostLogo || '';
    this.PreviousPlan = tenantDetails.PreviousPlan || '';
    this.SchemaID = tenantDetails.SchemaID || '';
    this.Slogan = tenantDetails.Slogan || '';
    this.StateId = tenantDetails.StateId || 0;
    this.SubDomain = tenantDetails.SubDomain || '';
    this.SubscriptionExpiredOn = tenantDetails.SubscriptionExpiredOn || '';
    this.SubscriptionRenewedAt = tenantDetails.SubscriptionRenewedAt || '';
    this.SubscriptionStartOn = tenantDetails.SubscriptionStartOn || '';
    this.SubscriptionStatus = tenantDetails.SubscriptionStatus || '';
    this.SupportEmail = tenantDetails.SupportEmail || '';
    this.SupportPhoneNumber = tenantDetails.SupportPhoneNumber || '';
    this.ThemeID = tenantDetails.ThemeID || '';
    this.UpdatedBy = tenantDetails.UpdatedBy || null;
    this.UpdatedOn = tenantDetails.UpdatedOn || null;
  }
}
